#!/bin/bash

docker rm -fv madness
docker build -t master-environment .
docker run -d -v /var/tmp/madnesscont/:/var/tmp/madnesscont -v /var/tmp/madnesscont/docker:/var/lib/docker --privileged --name=madness master-environment
